'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AISM.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 201 Albania
        '''202 Andorra
        '''203 Austria
        '''204 Azores
        '''205 Belgium
        '''206 Belarus
        '''207 Bulgaria
        '''208 Vatican City State
        '''209 Cyprus
        '''210 Cyprus
        '''211 Germany
        '''212 Cyprus
        '''213 Georgia
        '''214 Moldova
        '''215 Malta
        '''216 Armenia
        '''218 Germany
        '''219 Denmark
        '''220 Denmark
        '''224 Spain
        '''225 Spain
        '''226 France
        '''227 France
        '''228 France
        '''230 Finland
        '''231 Faroe Islands
        '''232 UK | Northern Ireland
        '''233 UK | Northern Ireland
        '''234 UK | Northern Ireland
        '''235 UK | Northern Ireland
        '''236 Gibraltar
        '''237 Greece
        '''238 Croatia
        '''239 Greece
        '''240 Greec [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property codes() As String
            Get
                Return ResourceManager.GetString("codes", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
